/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/UI/Button/Button.vue')['default']
    component: typeof import('vue')['component']
    Container: typeof import('./src/components/Container/Container.vue')['default']
    IconSprite: typeof import('./src/components/UI/IconSprite/IconSprite.vue')['default']
    Input: typeof import('./src/components/UI/Input/Input.vue')['default']
    Modal: typeof import('./src/components/UI/Modal/Modal.vue')['default']
    StatusFilter: typeof import('./src/components/StatusFilter/StatusFilter.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm/TaskForm.vue')['default']
    Tasks: typeof import('./src/components/Tasks/Tasks.vue')['default']
    TasksFormGenerate: typeof import('./src/components/TasksFormGenerate/TasksFormGenerate.vue')['default']
    TasksResult: typeof import('./src/components/TasksResult/TasksResult.vue')['default']
    TaskTable: typeof import('./src/components/TaskTable/TaskTable.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader/TheHeader.vue')['default']
    Window: typeof import('./src/components/Window/Window.vue')['default']
  }
}
